#!/usr/bin/env node
/**
 * Generate the committed showcase mesh:
 *
 *   node dist/tools/make-knot-obj.js [out.obj]
 *
 * A (2,3) torus knot swept with a circular tube, written as a Wavefront OBJ
 * with positions, smooth per-vertex normals and quad faces (the in-tree
 * loader fan-triangulates them). Deterministic pure math - no RNG, no
 * inputs, fixed-precision output - so the asset is reproducible from source
 * and the repository stays self-contained and unencumbered.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { add, cross, normalize, scale, sub, vec3, type Vec3 } from '../vec3.js';

const P = 2; // longitudinal winding
const Q = 3; // meridional winding
const TUBULAR = 128; // segments along the knot
const RADIAL = 16; // segments around the tube
const TUBE = 0.34; // tube radius

/** Centreline of the (P,Q) torus knot at parameter t in [0, 2 pi). */
function curve(t: number): Vec3 {
  const r = 2 + Math.cos(Q * t);
  return vec3(r * Math.cos(P * t), r * Math.sin(P * t), Math.sin(Q * t));
}

const out = process.argv[2] ?? 'assets/knot.obj';
const lines: string[] = [
  '# (2,3) torus knot generated by dist/tools/make-knot-obj.js',
  `# ${TUBULAR}x${RADIAL} segments, tube radius ${TUBE}`,
];

const positions: Vec3[] = [];
const normals: Vec3[] = [];
for (let i = 0; i < TUBULAR; i++) {
  const t = (2 * Math.PI * i) / TUBULAR;
  const eps = 0.001;
  const ahead = curve(t + eps);
  const behind = curve(t - eps);
  const centre = curve(t);
  // Frame from the first and second derivative directions (finite differences).
  const tangent = sub(ahead, behind);
  const accel = sub(add(ahead, behind), scale(centre, 2));
  const binormal = normalize(cross(tangent, accel));
  const normal = normalize(cross(binormal, tangent));
  for (let j = 0; j < RADIAL; j++) {
    const v = (2 * Math.PI * j) / RADIAL;
    const dir = add(scale(normal, Math.cos(v)), scale(binormal, Math.sin(v)));
    positions.push(add(centre, scale(dir, TUBE)));
    normals.push(dir);
  }
}

const f = (n: number): string => n.toFixed(6);
for (const p of positions) lines.push(`v ${f(p.x)} ${f(p.y)} ${f(p.z)}`);
for (const n of normals) lines.push(`vn ${f(n.x)} ${f(n.y)} ${f(n.z)}`);

/** 1-based OBJ index of tube vertex (i, j), both wrapping. */
const idx = (i: number, j: number): number => (i % TUBULAR) * RADIAL + (j % RADIAL) + 1;
for (let i = 0; i < TUBULAR; i++) {
  for (let j = 0; j < RADIAL; j++) {
    const a = idx(i, j);
    const b = idx(i + 1, j);
    const c = idx(i + 1, j + 1);
    const d = idx(i, j + 1);
    lines.push(`f ${a}//${a} ${b}//${b} ${c}//${c} ${d}//${d}`);
  }
}

const text = lines.join('\n') + '\n';
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, text);
process.stderr.write(
  `wrote ${out} (${positions.length} vertices, ${TUBULAR * RADIAL} quads, ${text.length} bytes)\n`,
);
